# Config file for automatic testing at travis-ci.org

dist: xenial

language: python

python: {% if '1.11' in cookiecutter.django_versions %}
  - "2.7"{% endif %}
  - "3.5"
  - "3.6"

matrix:
  fast_finish: true

install:
  - pip install -r requirements_test.txt
  - pip install tox-travis

before_script: flake8

script: tox

after_success: codecov
